classification_tasks:
    row_index:
        init_name: "row index"
        name: "row_index"
        hash_name: "row_index_hash"
        label_task: "multi-label"
    file:
        init_name: "path"
        name: "file"
        hash_name: "file_hash"
        label_task: "multi-label"
    column:
        init_name: "year"
        name: "column"
        hash_name: "column_hash"
        label_task: "multi-label"
    region:
        init_name: "region"
        name: "region"
        hash_name: "region_hash"
        label_task: "multi-label"
    tab:
        init_name: "tab"
        name: "tab"
        hash_name: "tab_hash"
        label_task: "multi-label"
    template_formula:
        init_name: "Calculation Equation"
        name: "template_formula"
        hash_name: "template_formula"
        label_task: "single-label"