classification_tasks:
    row_index:
        init_name: "row index"
        name: "row_index"
        hash_name: "row_index_hash"
        label_task: "multi-label"
        priority: 3
    file:
        init_name: "path"
        name: "file"
        hash_name: "file_hash"
        label_task: "multi-label"
        priority: 0
    column:
        init_name: "year"
        name: "column"
        hash_name: "column_hash"
        label_task: "multi-label"
        priority: 4
    region:
        init_name: "region"
        name: "region"
        hash_name: "region_hash"
        label_task: "multi-label"
        priority: 2
    tab:
        init_name: "tab"
        name: "tab"
        hash_name: "tab_hash"
        label_task: "multi-label"
        priority: 1
    template_formula:
        init_name: "Calculation Equation"
        name: "template_formula"
        hash_name: "template_formula"
        label_task: "single-label"
        priority: 5

models_dir: "data/exported_models/"
data_dir: "data/exported_data/"
test_df_name: "test_df_simulation.csv"